### ISSUE TITLE
makefile (operator?) error

### ISSUE THREAD

**Issue by rmm257** [ozagordi/shorah#13]
Hello, When I run the makefile on version 25f2dd5 (in Linux CentOS on the cluster),  I get this error:

making executable: fil 
*********************************
g++ filter_src/fil.c -o fil -Isamtools -Lsamtools -lbam -lm -lz -lgsl -lgslcblas 
samtools/libbam.a(bgzf.o): In function `mt_destroy':
/scicomp/home/bcv3/Downloads/ozagordi-shorah-25f2dd5/samtools/bgzf.c:458: undefined reference to `pthread_join'
samtools/libbam.a(bgzf.o): In function `bgzf_mt':
/scicomp/home/bcv3/Downloads/ozagordi-shorah-25f2dd5/samtools/bgzf.c:445: undefined reference to `pthread_create'
collect2: ld returned 1 exit status
make: *** [fil] Error 1

I do not get the same error in version 0.8.  

Best wishes,
Rebecca

**Comment by ozagordi** [comment]
Hi @rmm257,
I'm closing the issue now, assuming that you solved it.

**Comment by jttkim** [comment]
just a quick remark that (1) installing pthreads (or anything else) via `yum` works only on RedHat based distributions (such as CentOS), and also requires root privileges.
