### ISSUE TITLE
Errors ..

### ISSUE THREAD

**Issue by zusman** [ozagordi/shorah#17]
Dear Ozagordi,
I have been using Shorah for my viral data to identify true haplotypes. But it gives out these Error in the end. I am not sure why these errors are appearing. 

Traceback (most recent call last):
  File "/home/software/install/ShoRAH/shorah.py", line 194, in <module>
  for s in SeqIO.parse('%s_cor.popl' % in_stem, 'fasta'):
  File "/usr/lib64/python2.7/site-packages/Bio/SeqIO/__init__.py", line 342, in parse
  raise TypeError("Need a file handle, not a string (i.e. not a filename)")

Moreover, can you please tell which frequency for haplotype are considered to be significant. Because most of the haplotypes it makes have frequencies below 0.0113..

Makes thanks,

**Comment by ozagordi** [comment]
Hi!
Did you read [here](http://ozagordi.github.io/shorah/global.html)?
As for the error, I don't have much information to help. Some more detail?
