### ISSUE TITLE
how to run local mode

### ISSUE THREAD

**Issue by homopolymer** [ozagordi/shorah#18]
Hi, I am going to perform local analysis.  Is it correct that running shorah.py -r 'chr:100-400' to call local mode?

**Comment by ozagordi** [comment]
`shorah.py` will start a global run, _i.e._ local haplotypes plus haplotype phasing. If you want to skip haplotype phasing run `dec.py`. If read length is ~300, then you might want to run in amplicon mode with `amplian.py -r chr:100-400`.
