### ISSUE TITLE
Cygwin - long run time of amplian.py

### ISSUE THREAD

**Issue by Murskautuminen** [ozagordi/shorah#19]
Hello,

First of all: I am not very familiar with any programming or deeper details about bioinformatics. 

But: I am currently running the Shorah package inside Cygwin on a standard windows 7 terminal (32 GB RAM, core i7 4x 3.4 GHz). The installation of cygwin (64-bit) and assorted dependencies/libraries for Shorah/samtools (GLS, python, biopython, ncurses and a gcc compiler) went fine and I installed the Shorah Package without many problems. 

However, currently I am running the amplian.py script inside Cygwin and it is running already 2 days for a single mapped to reference sample of around 100.000 paired end reads (2x250) of a single PCR amplicon (+-400 bp) deep sequencing. Even more so, I am running the amplain.py script on a sorted bam file containing a highly covered (by paired ends) (88.000, as reported in coverage.txt) region of only 70 bp as defined by the -r input command (430-500).

> 0 ----------------------------|----|----------------------------------- 1190  Reference
> ............................--------|----|->.................................................  Read 1 
>................................ <---|----|-------...........................................   Read 2
>....................................430-500................................................   Defined Region (by -r)

Now I must admit that this sample might contain a very high amount of SNVs and indels of various sizes (also visible in the mapping), as it contains the region of genomic DNA of a polyclonal cell line that has extensively been cut by the CRISPR/Cas9 genome editing protein. 

This is my actual input command:
` ./amplian.py -b samples/N300/N300_S46a2.bam -f samples/XPO1.fasta -m 0.9 -x 200000 -r XPO1:430-500`

And after 48 hours it is still running the dirisampler. In addition the file: w-XPO1-430-500.smp is still updating every minute and increasing in size, the programme appears to be actively writing something inside this file (it is at iteration 14291 out of 30000?). Maybe i should have used the 90% coverage as the borders of some of the reads do not overlap with the specified region completely. 

In addition, I have noticed that I am unable to use multithreading over the different processing cores, as I appear to be able to use only 1 of the i7 cores as recognized by windows. But I guess the single scripts do not support multithreading over multiple cores? I do seem to be able to start a new terminal and run the script on a different core with a new input command. 

I was wondering if it is normal to run more than a few days for such a single sample like this on a desktop PC? Probably it is... . Now finally, the standard coverage of the script suggests to use around 50.000 reads, so would 100.000 reads be too high?

**Comment by Murskautuminen** [comment]
It has finished running after 4 days, but now I get an error: 

`$ ./amplian.py -b samples/N300/N300_S46a2.bam -f samples/XPO1.fasta -m 0.9 -x 400000 -r XPO1:430-500
./amplian.py:114: UserWarning: 76.8 % of untouched objects <should be around 90-95%>
  warnings.warn(unt_msg)
/home/u0092539/ozagordi-shorah/snv.py:127: UserWarning: posterior = 1.018 > 1
  warnings.warn('posterior = %4.3f > 1' % post)
/home/u0092539/ozagordi-shorah/snv.py:127: UserWarning: posterior = 1.011 > 1
  warnings.warn('posterior = %4.3f > 1' % post)
/home/u0092539/ozagordi-shorah/snv.py:127: UserWarning: posterior = 1.007 > 1
  warnings.warn('posterior = %4.3f > 1' % post)
/home/u0092539/ozagordi-shorah/snv.py:127: UserWarning: posterior = 1.004 > 1
  warnings.warn('posterior = %4.3f > 1' % post)
/home/u0092539/ozagordi-shorah/snv.py:127: UserWarning: posterior = 1.002 > 1
  warnings.warn('posterior = %4.3f > 1' % post)
/home/u0092539/ozagordi-shorah/snv.py:127: UserWarning: posterior = 1.001 > 1
  warnings.warn('posterior = %4.3f > 1' % post)
Traceback (most recent call last):
  File "./amplian.py", line 437, in <module>
    main(*args, **vars(options))
  File "./amplian.py", line 355, in main
    sigma=s, increment=1)
  File "/home/u0092539/ozagordi-shorah/snv.py", line 373, in main
    snpD_m = getSNV(ref_m, segCov_m, increment)
  File "/home/u0092539/ozagordi-shorah/snv.py", line 205, in getSNV
    cov = segCov[chrom + str(beg + incr)]
KeyError: 'XPO1500'`

**Comment by ozagordi** [comment]
Hi.
Lots of stuff to discuss! You figured out correctly a lot of the details already.
Yes, amplian runs on a single window and so it is not multithreaded. As you realised it was actually working, it just took very long. I would recommend one thing to begin with: run on much smaller samples. I doubt that a coverage of 10^5 is of any use because you are hitting the sequencing error rate anyway.

Once you see things going fine you could go to maybe 10^4 or so, maybe also resampling reads a few times to make sure that you have consistent results. We can discuss again the results. For example, you might want to run with an increased alpha, one or two orders of magnitude higher than the default.

Let me know.

**Comment by Murskautuminen** [comment]
Hello Ozagordi,

I have extracted 10% of the aligned reads in the bam file at random using samtools.
Now the programme runs much faster, but I start having problems with the snv.py again.

It returns the same error as before: 

`$ ~/ozagordi-shorah/snv.py -r XPO1.fasta -b N300/N300_S46a-0.1index.bam
/home/u0092539/ozagordi-shorah/snv.py:127: UserWarning: posterior = 1.003 > 1
  warnings.warn('posterior = %4.3f > 1' % post)
Traceback (most recent call last):
  File "/home/u0092539/ozagordi-shorah/snv.py", line 445, in <module>
    main(*args, **vars(options))
  File "/home/u0092539/ozagordi-shorah/snv.py", line 373, in main
    snpD_m = getSNV(ref_m, segCov_m, increment)
  File "/home/u0092539/ozagordi-shorah/snv.py", line 205, in getSNV
    cov = segCov[chrom + str(beg + incr)]
KeyError: 'XPO1500'
`

**Comment by ozagordi** [comment]
The warning is just a warning, we can ignore it for now.

`snv.py` is not really meant to be called by itself. Is this amplicon based? How long is the amplicon? How long are the reads? If amplicon is ~shorter than the read length I would run `amplian.py`. Do you have coverage everywhere? Did you check with `samtools tview`?

**Comment by Murskautuminen** [comment]
Hello Ozagordi,

Thank you for the very fast reply. I am currently working and things seem to work with smaller samples containing 20.000 to 40.000. Running the amplian.py works and I was too quick to ask for help!

Thank you again, if I have any problems in the future, I will not hesitate to comment here :)

**Comment by ozagordi** [comment]
Happy to hear. So I close this for now.

Best.
