### ISSUE TITLE
Windowsshift

### ISSUE THREAD

**Issue by saminhf** [ozagordi/shorah#23]
Hi,
I have a question about definition of windows shift in your program. Based on your article if I window shift=3, it means each position is covered 3 times. Then based on this definition if I have 6000nt for reference, the number of created files (support file) should be 6000-readlength/3 but I just have 93 files. Could you please explain it more?
Thanks

**Comment by ozagordi** [comment]
The other parameter dictating how many windows will be made is the length of the window. If the  region to cover is 6000 and you use a window length 201 then there will be ~30 non overlapping windows. Shorah works with overlapping windows and window shift sets how many overlapping window you have at each position, so if you have window shift = 3 then you will have ~90 windows in total (the approximation coming from how the ends are dealt with).
